In [1]:
import numpy as np
import pandas as pd

In [10]:
# ndarray object 생성
# shape : 배열의 구조값 , ndim : 차원값 확인
# 1. array function 사용
array1 = np.array([1,2,3])
print(type(array1))
# print(dir(array1)) # dir : 오브젝트 멤버(변수, 메소드) 목록 출력 함수
print('array shape : ',array1.shape)
print('array dim : ',array1.ndim)


<class 'numpy.ndarray'>
array shape :  (3,)
array dim :  1


In [13]:
list_2d = [[1,2,3],[4,5,6]]
print(list_2d) # list object
array2 = np.array(list_2d) # ndarray object 
print(array2)
print('array2 shape : ', array2.shape) # 배열의 구조 출력
print('array2 dim : ', array2.ndim) # 차원을 출력


[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
array2 shape :  (2, 3)
array2 dim :  2


In [20]:
list_2d=[[1,2,'test']]
array3=np.array(list_2d)
print(array3)
print(array3.shape) # 1 X 3 배열, 배열 구조
print(array3.ndim) # 2차원 배열
print(array3.dtype)

[['1' '2' 'test']]
(1, 3)
2
<U21


In [26]:
# 타입 변경 : astype('변경할타입') 메소드 => ndarray object 안에 있는 메소드
array_int=np.array([1,2,3], dtype='int8') # 정수 타입
print(array_int.dtype)
# 실수로 변환
array_float=array_int.astype('float64')
print(array_float.dtype)
# 정수로 변환
arrry_int1=array_float.astype('int8')
print(arrry_int1.dtype)

int8
float64
int8


In [29]:
# ndarray object 생성
# 2. arange, zeros, ones function
# 2.1 arange([start], end, [step])
seq_arr=np.arange(10)
print(seq_arr)
print(seq_arr.dtype)
print(seq_arr.shape)
print(seq_arr.ndim)


[0 1 2 3 4 5 6 7 8 9]
int64
(10,)
1


In [32]:
# 2.2 zeros((행,열)) : ndarray object 생성하고 0으로 초기화
zero_arr=np.zeros((3,2), dtype='int32')
print(zero_arr)
print(zero_arr.shape)
print(zero_arr.ndim)

[[0 0]
 [0 0]
 [0 0]]
(3, 2)
2


In [34]:
# 2.3 ones((행,열)) : ndarray object 생성하고 1로 초기화
# one_arr=np.ones((3,2)) # default float64
one_arr=np.ones((3,2), dtype='int32') 
print(one_arr)
print(one_arr.shape)
print(one_arr.dtype)

[[1 1]
 [1 1]
 [1 1]]
(3, 2)
int32


In [37]:
# 차원과 크기 변경 : reshape()메소드
arr1 = np.arange(10) # 10개, 1차원, 10,
print(arr1)
arr2=arr1.reshape(2,5) # 2행 5열 변경
print(arr2)
arr3=arr1.reshape(5,2)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [40]:
# reshape() error
print(arr1)
# arr_err=arr1.reshape(3,4)

[0 1 2 3 4 5 6 7 8 9]


In [48]:
# reshape 유용한 기능
data_num=1000005
arr1=np.arange(data_num)

c_n=int(data_num/5)
print(arr1)
# 5열짜리로 만들고자 한다
print(arr1.reshape(c_n,5))
print(arr1.reshape(-1,5)) # 5개 열로 변환,  -1 => ?
print(arr1.reshape(5,-1)) # 5개 형으로 변환

[      0       1       2 ... 1000002 1000003 1000004]
[[      0       1       2       3       4]
 [      5       6       7       8       9]
 [     10      11      12      13      14]
 ...
 [ 999990  999991  999992  999993  999994]
 [ 999995  999996  999997  999998  999999]
 [1000000 1000001 1000002 1000003 1000004]]
[[      0       1       2       3       4]
 [      5       6       7       8       9]
 [     10      11      12      13      14]
 ...
 [ 999990  999991  999992  999993  999994]
 [ 999995  999996  999997  999998  999999]
 [1000000 1000001 1000002 1000003 1000004]]
[[      0       1       2 ...  199998  199999  200000]
 [ 200001  200002  200003 ...  399999  400000  400001]
 [ 400002  400003  400004 ...  600000  600001  600002]
 [ 600003  600004  600005 ...  800001  800002  800003]
 [ 800004  800005  800006 ... 1000002 1000003 1000004]]


In [59]:
arr1=np.arange(12) # 12개
# print(arr1)
# print(arr1.ndim, '차원')

# arr2=arr1.reshape(3,4)
# print(arr2)
# print(arr2.ndim,'차원')

arr3=arr1.reshape(2,2,3)
# print(arr3)
# print(arr3.ndim,'차원')

# arr4=arr3.reshape(-1,4)
# print(arr4)
# print(arr4.ndim,'차원')

arr5=arr3.reshape(4,-1) # 4행짜리 ndarray 생성
print(arr5)

arr6=arr3.reshape(-1)
print(arr6)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [64]:
# ndarray => list로 추출
print(arr6)
print(type(arr6))
print(arr6.tolist())
print(type(arr6))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
<class 'numpy.ndarray'>


In [70]:
# 인덱싱 어마무시 중요
# 1. 단일값 추출
arr1=np.arange(1,10)
print(arr1)
value=arr1[2]
value1=arr1[-1]
arr1[2]=13
print(arr1)
print(value)
print(value1)
print(type(value))

[1 2 3 4 5 6 7 8 9]
[ 1  2 13  4  5  6  7  8  9]
3
9
<class 'numpy.int64'>


In [73]:
# 2차원데이터 인덱싱
arr1d=np.arange(1,10)
print(arr1d) # 1차원
arr2d=arr1d.reshape(3,3)
print(arr2d) # 2차원
print(arr2d[1,2]) # arr2d[행,열]

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [77]:
# 슬라이싱 : 연속된 여러개 추출
arr1 = np.arange(1,10)
print(arr1)
arr3=arr1[0:3]
print(arr3)
print(type(arr3))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [79]:
# 확장 사용 => 시작인덱스 : 끝인덱스 <= 생략 형태
print(arr1)

arr4=arr1[:3] # [처음부터:3] 동일
print(arr4)

arr5=arr1[3:] # [3:끝까지] 동일
print(arr5)

arr6=arr1[:] # [처음부터:끝까지] 동일
print(arr6)

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [82]:
# 2차원 데이터 슬라이싱 [행,열]
print(arr2d)
print(arr2d[1:,1:])
print(arr2d[1:,:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]
[[4 5 6]
 [7 8 9]]


In [85]:
print(arr2d)
print(arr2d[0])
print(arr2d[1])
print(arr2d[2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[4 5 6]
[7 8 9]


In [91]:
### 3. 팬시 색인 : 비연속된 데이터 추출시 사용
print(arr2d)
print(arr2d[[0,0,2,2],[0,2,0,2]]) # [[행선택 0,2],[열선택 0,2]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 3 7 9]


In [96]:
# 블린(boolean) 인덱싱
arr1d=np.arange(1,10)
print(arr1d)
print(arr1d > 5)
print(arr1d[[False, False, False, False, False,  True,  True,  True,  True]])
print(arr1d[arr1d>5])


[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
[6 7 8 9]
[6 7 8 9]


In [97]:
# 32page 특정 조건에 맞는 데이터 추출 
boolean_indexes=np.array([False,False,False,False,False,True,True,True,True])
print(boolean_indexes)

[False False False False False  True  True  True  True]


In [99]:
print(arr1d)
print(arr1d[boolean_indexes])

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]


In [105]:
# 행렬의 정렬 : sort() => 메모리에 정렬 결과 도출된다
# np.sort() 함수, ndarray.sort() 메소드
org_arr=np.array([3,1,9,5])
print(org_arr) # [3 1 9 5]
# np.sort(ndarray) 
sort_arr=np.sort(org_arr)
print(sort_arr)
print(org_arr) # [3 1 9 5] 원본 변경 안되었다

# ndarray.sort()
sort_arr=org_arr.sort()
print(sort_arr) # 정렬 후 ndarray
print(org_arr) # 정렬전 ndarray  원본이 정렬된다

[3 1 9 5]
[1 3 5 9]
[3 1 9 5]
None
[1 3 5 9]


In [111]:
# 위 정렬에 문제점 한개 있다
org_arr=np.array([3,1,9,5])
sort_arr_asc=np.sort(org_arr)
print(org_arr)
print('Asc : ',sort_arr_asc)
print('Desc : ',sort_arr_asc[::-1]) # [처음부터:끝까지:스텝]
print(org_arr)

[3 1 9 5]
Asc :  [1 3 5 9]
Desc :  [9 5 3 1]
[3 1 9 5]


In [112]:
# 2차원 정렬
list_2d=[[8,12],[7,1]]
print(list_2d)
arr2d=np.array(list_2d)
print(arr2d)

[[8, 12], [7, 1]]
[[ 8 12]
 [ 7  1]]


In [114]:
print(arr2d)
print(np.sort(arr2d,axis=1)) # axis=1 열방향으로 정렬
print(np.sort(arr2d,axis=0)) # axis=0 행방향으로 정렬


[[ 8 12]
 [ 7  1]]
[[ 8 12]
 [ 1  7]]
[[ 7  1]
 [ 8 12]]


In [123]:
# argsort() : 정렬된 행렬의 인덱스를 반환한다
print('원본데이터 : ',org_arr)
max_index=np.argmax(org_arr)
print('최대값의 인덱스 : ',max_index)
print('최대값 : ',org_arr[max_index])

print('원본데이터 : ',org_arr)
min_index=np.argmin(org_arr)
print('최소값의 인덱스 : ',min_index)
,print('최소값 : ',org_arr[min_index])

원본데이터 :  [3 1 9 5]
최대값의 인덱스 :  2
최대값 :  9
원본데이터 :  [3 1 9 5]
최소값의 인덱스 :  1
최소값 :  1


In [132]:
print('원본데이터 : ',org_arr)
sort_index=np.argsort(org_arr) # 정렬한 인덱스 반환
print('ASC 정렬한 인덱스 : ', sort_index)
print('ASC 정렬한 인덱스의 타입 : ', type(sort_index))
print('DESC 정렬한 인덱스 : ', sort_index[::-1])

print('ASC 정렬한 결과',org_arr[sort_index]),
print('DESC 정렬한 결과',org_arr[sort_index[::-1]])

원본데이터 :  [3 1 9 5]
ASC 정렬한 인덱스 :  [1 0 3 2]
ASC 정렬한 인덱스의 타입 :  <class 'numpy.ndarray'>
DESC 정렬한 인덱스 :  [2 3 0 1]
ASC 정렬한 결과 [1 3 5 9]
DESC 정렬한 결과 [9 5 3 1]


In [146]:
# argsort 사용 예제
# name_arr=['홍길동','고길동','마이꼴','둘리','희동'] #list
# score_arr=[78,95,84,98,88] # list
name_arr=np.array(['홍길동','고길동','마이꼴','둘리','희동']) #list
score_arr=np.array([78,95,84,98,88]) # list

max_idx=np.argmax(score_arr)
# 최대 점수
print('최대 점수 ',score_arr[max_idx])
# 최대 점수 학생이름 출력
print('최대 점수 학생명 :',name_arr[max_idx])

# 점수별(DESC) 학생명 출력
desc_sort_idx=np.argsort(score_arr)[::-1] # ndarray 
# print(type(asc_sort_idx))
# print(type(asc_sort_idx[0]))
print('점수순(DESC) 학생명 :', name_arr[desc_sort_idx])

최대 점수  98
최대 점수 학생명 : 둘리
점수순(DESC) 학생명 : ['둘리' '고길동' '희동' '마이꼴' '홍길동']


In [149]:
# 전치 행렬
A = np.array([
      [1,2]
    , [3,4]
])
print(A)
print(A.transpose())
print(A.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
